name: opti_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  
  # Core UI packages
  fl_chart: ^0.70.2
  carousel_slider: ^5.0.0
  flutter_colorpicker: ^1.1.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  animate_do: ^4.1.1
  flutter_animate: ^4.2.0
  shimmer: ^3.0.0
  swipe_to: ^1.0.6

  # Networking and data handling
  http: ^1.3.0
  dio: ^5.4.0
  cached_network_image: ^3.3.1
  
  # State management
  provider: ^6.0.5
  get: ^4.6.6
  equatable: ^2.0.7
  dartz: ^0.10.1
  
  # Storage
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^9.0.0
  path: ^1.8.3
  
  # Authentication
  flutter_facebook_auth: ^7.1.1
  google_sign_in: ^6.2.2
  jwt_decoder: ^2.0.1
  
  # Image and file
  image_picker: ^1.0.7
  file_picker: ^9.1.0
  
  # Location and Maps
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  google_maps_flutter: ^2.2.3
  flutter_polyline_points: ^2.0.0
  
  # Date, time and formatting
  intl: ^0.20.2
  time_range_picker: ^2.3.0
  
  # PDF handling
  pdf: ^3.10.0
  open_file: ^3.3.1
  flutter_pdfview: ^1.3.2
  
  # Notifications and sharing
  onesignal_flutter: ^5.3.0
  share_plus: ^10.1.4
  url_launcher: ^6.3.1
  
  # Camera and ML
  camera: ^0.11.0+2
  google_ml_kit: ^0.19.0
  google_mlkit_face_detection: ^0.12.0
  google_mlkit_commons: ^0.9.0
  google_mlkit_barcode_scanning: ^0.13.0
  
  # Permissions
  permission_handler: ^11.0.1

  # Remove model_viewer_plus if you don't need 3D model viewing
  # model_viewer_plus: ^1.9.0
  
  # Keep only if you need 3D functionality
  flutter_3d_controller: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/Virtualreality.gif
    - assets/images/AR1.avif
    - assets/images/homme.avif
    - assets/images/femme.avif
    - assets/images/image.jpg
    - assets/images/b1.jpeg
    - assets/images/b2.jpeg
    - assets/images/sun.jpeg
    - assets/images/vu.jpeg
    - assets/images/
    - assets/
    - assets/images/login_illustration.png
    - assets/3d_models/scene.gltf
    - assets/3d_models/scene.bin